### ISSUE TITLE
Need help :/

### ISSUE THREAD

**Issue by developer-farhan** [evilevidenz/eeffects#1]
im trying to create a message effect where there is text inside container but the container is on fire to give on fire message effect but I just can not get it to work

//MyCode

class FireChatBubble extends StatefulWidget {
  @override
  _FireChatBubbleState createState() => _FireChatBubbleState();
}

class _FireChatBubbleState extends State<FireChatBubble> {
  EScene scene;

  @override
  void initState() {
    scene = EScene(
      width: 0,
      height: 0,
      effects: [
        EFire(
            EGradient([
              EColorShift([Colors.red], 0),
              EColorShift([Colors.orange.shade800], 0),
              EColorShift([Colors.orange.shade600], 0)
            ]),
            EGradient([
              EColorShift([Color.fromARGB(10, 100, 100, 100)], 0)
            ]),
            EGradient([
              EColorShift([Color.fromARGB(20, 140, 100, 60)], 0),
              EColorShift([Color.fromARGB(10, 140, 100, 60)], 0)
            ]),
            1,
            0,
            ERelativePos(0.5, 0.5),
            EVector2D(0, -1),
            ERelative(30, ERelative.absolute),
            ERelative(40, ERelative.absolute),
            ERelative(2, ERelative.absolute),
            ERelative(40, ERelative.absolute),
            ERelative(150, ERelative.absolute),
            ERelative(8, ERelative.absolute)),
      ],
      darkness: EColorShift([Color.fromARGB(255, 0, 0, 0)], 0),
      afterUpdate: () {},
      beforeUpdate: () {},
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 50,
      width: 70,
      color: Colors.transparent,
      child: LayoutBuilder(builder: (context, size) {
        scene.resize(size.biggest.width, size.biggest.height);
        return Container(
          child: Stack(
            alignment: Alignment.center,
            children: [scene, Text('hey There')],
          ),
        );
      }),
    );
  }
}

and this is how it looks like. its awful just a square with orange gradient 
<img width="62" alt="Screenshot 2022-02-01 at 13 39 12" src="https://user-images.githubusercontent.com/82877513/151936815-de746e81-408f-4418-ac37-ee8c9f10230e.png">
ent

**Comment by leonl42** [comment]
The problem is the layout order. The relatively small container is the parent of the EScene. Everything which is drawn in the scene will be relative to its parent, the container.

So the EScene, and with that the flame effect, is cut accordingly to make it fit into the container. You have a few options to fix this:

- Make the container bigger
- Make the flame smaller
- Make the EScene parent of the container

**Comment by developer-farhan** [comment]
could you give me an example code with text inside container so I can play around with values to fully understand? and compare with example code   that would help me alot

**Comment by developer-farhan** [comment]
Tried this made container bigger and scene smaller but no results it still shows like a box on phone



Container(
        color: Colors.grey[700],
        height: 100,
        width: 100,
        child: Center(
          child: EScene(
            width: 60,
            height: 60,
            effects: [
              EFire(
                  EGradient([
                    EColorShift([Colors.red], 0),
                    EColorShift([Colors.orange.shade800], 0),
                    EColorShift([Colors.orange.shade600], 0)
                  ]),
                  EGradient([
                    EColorShift([Color.fromARGB(10, 100, 100, 100)], 0)
                  ]),
                  EGradient([
                    EColorShift([Color.fromARGB(20, 140, 100, 60)], 0),
                    EColorShift([Color.fromARGB(10, 140, 100, 60)], 0)
                  ]),
                  1,
                  0,
                  ERelativePos(0.5, 0.5),
                  EVector2D(0, -1),
                  ERelative(30, ERelative.absolute),
                  ERelative(40, ERelative.absolute),
                  ERelative(2, ERelative.absolute),
                  ERelative(40, ERelative.absolute),
                  ERelative(150, ERelative.absolute),
                  ERelative(8, ERelative.absolute)),
            ],
            darkness: EColorShift([Color.fromARGB(255, 0, 0, 0)], 0),
            afterUpdate: () {},
            beforeUpdate: () {},
          ),
          
          
          
        )
<img width="191" alt="Screenshot 2022-02-02 at 13 37 19" src="https://user-images.githubusercontent.com/82877513/152120043-7f63f557-b9f0-4235-83b0-d3bfaa6f14b6.png">
)

**Comment by leonl42** [comment]
//MyCode

class FireChatBubble extends StatefulWidget {
@OverRide
_FireChatBubbleState createState() => _FireChatBubbleState();
}

class _FireChatBubbleState extends State {
EScene scene;

@OverRide
void initState() {
scene = EScene(
width: 0,
height: 0,
effects: [
EFire(
EGradient([
EColorShift([Colors.red], 0),
EColorShift([Colors.orange.shade800], 0),
EColorShift([Colors.orange.shade600], 0)
]),
EGradient([
EColorShift([Color.fromARGB(10, 100, 100, 100)], 0)
]),
EGradient([
EColorShift([Color.fromARGB(20, 140, 100, 60)], 0),
EColorShift([Color.fromARGB(10, 140, 100, 60)], 0)
]),
1,
0,
ERelativePos(0.5, 0.5),
EVector2D(0, -1),
ERelative(30, ERelative.absolute),
ERelative(40, ERelative.absolute),
ERelative(2, ERelative.absolute),
ERelative(40, ERelative.absolute),
ERelative(150, ERelative.absolute),
ERelative(8, ERelative.absolute)),
],
darkness: EColorShift([Color.fromARGB(255, 0, 0, 0)], 0),
afterUpdate: () {},
beforeUpdate: () {},
);
super.initState();
}

@OverRide
Widget build(BuildContext context) {
return Container(
height: 500,
width: 700,
color: Colors.transparent,
child: LayoutBuilder(builder: (context, size) {
scene.resize(size.biggest.width, size.biggest.height);
return Container(
child: Stack(
alignment: Alignment.center,
children: [scene, Text('hey There')],
),
);
}),
);
}
}

**Comment by developer-farhan** [comment]
so I tested it out and it works at your height and width 

but the height and width takes more than half the screen. so I shrieked it down to 

height 60 and width 80.  keeping the same difference as your height and width  and then it goes back to looking like a square.  also the flame moves once and then gets stuck and I get error in debug 



======== Exception caught by animation library =====================================================
The following ConcurrentModificationError was thrown while notifying listeners for AnimationController:
Concurrent modification during iteration: Instance(length:19) of '_GrowableList'.

When the exception was thrown, this was the stack: 
#0      ListIterator.moveNext (dart:_internal/iterable.dart:334:7)
#1      EFire.update (package:eeffects/eEffect/effects/fire/fire.dart:163:33)
#2      ESceneState.update.<anonymous closure> (package:eeffects/eEffect/scene/scene.dart:93:19)
#3      State.setState (package:flutter/src/widgets/framework.dart:1267:30)
#4      ESceneState.update (package:eeffects/eEffect/scene/scene.dart:89:5)
...
The AnimationController notifying listeners was: AnimationController#9f793(⏮ 0.000; paused)
====================================================================================================

I am attaching 2 media. one of how it looks with height 60 and width 80 and one to show case the flame movement issue

https://user-images.githubusercontent.com/82877513/152125723-e464c3cb-5c30-40aa-ba36-9f1fa5bf50dd.mov

<img width="87" alt="Screenshot 2022-02-02 at 14 12 56" src="https://user-images.githubusercontent.com/82877513/152125736-0e2dd7c2-9e96-4110-a48f-2fe0dfa05591.png">

**Comment by developer-farhan** [comment]
any update? I really want to use the flame and lightening effect that would be so cool
